sudo: required
services:
  - docker

before_install:
  - docker build -t chemplife/docker-react -f Dockerfile.dev .

script:
  - docker run chemplife/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-048447239686"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY



DockerReact-env.eba-iwtcm5et.us-east-2.elasticbeanstalk.com